language: cpp

os: linux
dist: bionic
arch:
  - amd64
  - arm64

compiler:
  - clang
  - gcc

addons:
  apt:
    update: true
    packages:
      - cmake
      - gcc
      - g++
      - clang

jobs:
  include:
    - os: osx
      osx_image: xcode11.2
      compiler: clang
      arch: amd64
    - os: osx
      osx_image: xcode11.2
      compiler: gcc
      arch: amd64
      env:
        - MATRIX_EVAL="brew install gcc"


script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest