language: cpp

os: linux
dist: bionic
arch:
  - amd64
  - arm64

compiler:
  - clang
  - gcc

addons:
  apt:
    update: true
    packages:
      - cmake
      - gcc
      - g++
      - clang
      - openjdk-11-jdk
      - libatk-wrapper-java-jni

jobs:
  include:
    - os: osx
      osx_image: xcode11.2
      compiler: clang
      arch: amd64
    - os: osx
      osx_image: xcode11.2
      compiler: gcc
      arch: amd64
      env:
        - MATRIX_EVAL="brew install gcc && brew tap adoptopenjdk/openjdk && brew cask install adoptopenjdk11"


script:
  - mkdir build
  - cd build
  - cmake .. `if [ "$TRAVIS_CPU_ARCH" != "arm64" ]; then echo "-DENABLE_JNI_TOOLS=TRUE"; fi`
  - cmake --build .
  - ctest