//
// Created by ilya on 08.11.2019.
//

#ifndef NLANG_VERSION_HPP
#define NLANG_VERSION_HPP

#define NLANG_VERSION_MAJOR 0
#define NLANG_VERSION_MINOR 0
#define NLANG_VERSION_PATCH 0

#define NLANG_VERSION "0.0.0"
#define NLANG_BUILD_COMPILER_ID "GNU"
#define NLANG_BUILD_COMPILER_VERSION "9.2.1"
#define NLANG_BUILD_GIT_REVISION "eeef9b4"


#endif //NLANG_VERSION_HPP
