/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nlang_JNI */

#ifndef _Included_org_nlang_JNI
#define _Included_org_nlang_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_nlang_JNI
 * Method:    tokenize
 * Signature: (Ljava/lang/CharSequence;IILjava/util/TreeMap;)V
 */
JNIEXPORT void JNICALL Java_org_nlang_JNI_tokenize
  (JNIEnv *, jclass, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
